export const GET_PATIENTS_FETCHING = 'GET_PATIENTS_FETCHING';
export const GET_PATIENTS_FULFILLED = 'GET_PATIENTS_FULFILLED';
export const GET_PATIENTS_REJECTED = 'GET_PATIENTS_REJECTED';

export const ADD_PATIENT_FETCHING = 'ADD_PATIENT_FETCHING';
export const ADD_PATIENT_FULFILLED = 'ADD_PATIENT_FULFILLED';
export const ADD_PATIENT_REJECTED = 'ADD_PATIENT_REJECTED';

export const UPDATE_PATIENT_FETCHING = 'UPDATE_PATIENT_FETCHING';
export const UPDATE_PATIENT_FULFILLED = 'UPDATE_PATIENT_FULFILLED';
export const UPDATE_PATIENT_REJECTED = 'UPDATE_PATIENT_REJECTED';

export const DELETE_PATIENT_FETCHING = 'DELETE_PATIENT_FETCHING';
export const DELETE_PATIENT_FULFILLED = 'DELETE_PATIENT_FULFILLED';
export const DELETE_PATIENT_REJECTED = 'DELETE_PATIENT_REJECTED';

export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
